# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xetera/projects/Serendipity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xetera/projects/Serendipity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xetera/projects/Serendipity/CMakeFiles /home/xetera/projects/Serendipity/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xetera/projects/Serendipity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Serendipity

# Build rule for target.
Serendipity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Serendipity
.PHONY : Serendipity

# fast build rule for target.
Serendipity/fast:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/build
.PHONY : Serendipity/fast

src/bookinfo.o: src/bookinfo.cpp.o

.PHONY : src/bookinfo.o

# target to build an object file
src/bookinfo.cpp.o:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/bookinfo.cpp.o
.PHONY : src/bookinfo.cpp.o

src/bookinfo.i: src/bookinfo.cpp.i

.PHONY : src/bookinfo.i

# target to preprocess a source file
src/bookinfo.cpp.i:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/bookinfo.cpp.i
.PHONY : src/bookinfo.cpp.i

src/bookinfo.s: src/bookinfo.cpp.s

.PHONY : src/bookinfo.s

# target to generate assembly for a file
src/bookinfo.cpp.s:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/bookinfo.cpp.s
.PHONY : src/bookinfo.cpp.s

src/cashier.o: src/cashier.cpp.o

.PHONY : src/cashier.o

# target to build an object file
src/cashier.cpp.o:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/cashier.cpp.o
.PHONY : src/cashier.cpp.o

src/cashier.i: src/cashier.cpp.i

.PHONY : src/cashier.i

# target to preprocess a source file
src/cashier.cpp.i:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/cashier.cpp.i
.PHONY : src/cashier.cpp.i

src/cashier.s: src/cashier.cpp.s

.PHONY : src/cashier.s

# target to generate assembly for a file
src/cashier.cpp.s:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/cashier.cpp.s
.PHONY : src/cashier.cpp.s

src/invmenu.o: src/invmenu.cpp.o

.PHONY : src/invmenu.o

# target to build an object file
src/invmenu.cpp.o:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/invmenu.cpp.o
.PHONY : src/invmenu.cpp.o

src/invmenu.i: src/invmenu.cpp.i

.PHONY : src/invmenu.i

# target to preprocess a source file
src/invmenu.cpp.i:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/invmenu.cpp.i
.PHONY : src/invmenu.cpp.i

src/invmenu.s: src/invmenu.cpp.s

.PHONY : src/invmenu.s

# target to generate assembly for a file
src/invmenu.cpp.s:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/invmenu.cpp.s
.PHONY : src/invmenu.cpp.s

src/mainmenu.o: src/mainmenu.cpp.o

.PHONY : src/mainmenu.o

# target to build an object file
src/mainmenu.cpp.o:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/mainmenu.cpp.o
.PHONY : src/mainmenu.cpp.o

src/mainmenu.i: src/mainmenu.cpp.i

.PHONY : src/mainmenu.i

# target to preprocess a source file
src/mainmenu.cpp.i:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/mainmenu.cpp.i
.PHONY : src/mainmenu.cpp.i

src/mainmenu.s: src/mainmenu.cpp.s

.PHONY : src/mainmenu.s

# target to generate assembly for a file
src/mainmenu.cpp.s:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/mainmenu.cpp.s
.PHONY : src/mainmenu.cpp.s

src/reports.o: src/reports.cpp.o

.PHONY : src/reports.o

# target to build an object file
src/reports.cpp.o:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/reports.cpp.o
.PHONY : src/reports.cpp.o

src/reports.i: src/reports.cpp.i

.PHONY : src/reports.i

# target to preprocess a source file
src/reports.cpp.i:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/reports.cpp.i
.PHONY : src/reports.cpp.i

src/reports.s: src/reports.cpp.s

.PHONY : src/reports.s

# target to generate assembly for a file
src/reports.cpp.s:
	$(MAKE) -f CMakeFiles/Serendipity.dir/build.make CMakeFiles/Serendipity.dir/src/reports.cpp.s
.PHONY : src/reports.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Serendipity"
	@echo "... src/bookinfo.o"
	@echo "... src/bookinfo.i"
	@echo "... src/bookinfo.s"
	@echo "... src/cashier.o"
	@echo "... src/cashier.i"
	@echo "... src/cashier.s"
	@echo "... src/invmenu.o"
	@echo "... src/invmenu.i"
	@echo "... src/invmenu.s"
	@echo "... src/mainmenu.o"
	@echo "... src/mainmenu.i"
	@echo "... src/mainmenu.s"
	@echo "... src/reports.o"
	@echo "... src/reports.i"
	@echo "... src/reports.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

